alias agfr='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/agfr'
alias adfr='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/adfr'
alias agfrgui='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/agfrgui'
alias autosite='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/autosite'
alias about='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/about'
alias prepare_receptor='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/prepare_receptor'
alias prepare_ligand='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/prepare_ligand'
alias pythonsh='/home/ubuntu/Vina-CUDA/tools/adfr/ADFRsuite-1.0/bin/pythonsh'
